spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alert_case_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

external:
  reporting-service:
    url: http://localhost:8088/sar/ingest-report
